project:
  type: website
  output-dir: docs

website:
  title: "mysite"
  page-footer: 
    left: "Copyright 2025, James Thurgood"
    center: "The views and opinions expressed are my own and do not reflect my employer." 
  navbar:
    left:
      - href: home/index.qmd
        text: Home
      - blog/blog.qmd

format:
  html:
    theme: 
      light: cosmo
      dark: cyborg
    code-overflow: wrap
    toc: true
    linestretch: 2
    html-math-method: katex

execute:
  freeze: auto


