project:
  type: website
  output-dir: docs

website:
  title: "mysite"
  page-footer: 
    left: "Copyright 2024, James Thurgood"
    center: "The views and opinions expressed are my own and do not reflect my employer." 
  navbar:
    left:
      - href: home/index.qmd
        text: Home
      - blog/blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


